name: Build Executables

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            os_name: Windows
          - os: ubuntu-latest
            os_name: Linux
          - os: macos-latest
            os_name: macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: true
      
      - name: Set up UV
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: uv sync

      - name: Build executable
        run: uvx pyinstaller --onedir
          --name "DFMetadataCustomizer"
          --contents-directory "lib"
          --add-data "presets:presets"
          --noconsole
          --noconfirm
          --clean
          "df_metadata_customizer/__main__.py"

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: DFMetadataCustomizer-${{ matrix.os_name }}
          path: dist/DFMetadataCustomizer/